INSERT INTO users
    (id, username, email, password)
VALUES
    (DEFAULT, 'Zach', 'zach@zach.com', 'zach'),
    (DEFAULT, 'Daniel', 'daniel@daniel.com', 'daniel'),
    (DEFAULT, 'Nep', 'nep@nep.com', 'nep');

INSERT INTO categories
    (id, name, description)
VALUES
    (DEFAULT, 'Arithmetic and Algebraic Operations', 'algebra'),
    (DEFAULT, 'Inequalities', 'inequalities'),
    (DEFAULT, 'Trigonometric Functions', 'trigonometry'),
    (DEFAULT, 'Logarithmic and Exponential Functions', 'logarithms');

-- algebra manual 12
INSERT INTO "public"."problems"("id","statement","type","answer_representation","answer_value","solution","category_id")
VALUES
(DEFAULT,E'CkJ5IGNvbXBsZXRpbmcgdGhlIHNxdWFyZSwgdGhlIHBvbHlub21pYWwgJHheMi02eCs0JCBjYW4gYmUgd3JpdHRlbiBpbiB0aGUgZm9ybSAkKHgtYSleMitiJC4gRXhwcmVzcyAkYSQgYW5kICRiJCBhcyBpbnRlZ2Vycy4K',E'manual_ordered',E'CiRhPTMsIGI9LTUkCg==',E'{a,3,b,-5}',E'CkNvbnNpZGVyIHRoZSBmb2xsb3dpbmc6ClxiZWdpbnthbGlnbip9CnheMi02eCs0CiY9ICh4XjItNngrOSkrNC05ICYgXHRleHR7KGFkZCBhbmQgc3VidHJhY3QgJCgtNi8yKV4yJCl9XFxbMC41ZW1dCiY9ICh4LTMpXjItNSAmIFx0ZXh0eyhmYWN0b3IpfVxcWzAuNWVtXQomPSAoeC0zKV4yKygtNSkuICYgXHRleHR7KHdyaXRlIGluIGRlc2lyZWQgZm9ybSl9ClxlbmR7YWxpZ24qfQpIZW5jZSwgJGE9MyQsIGFuZCAkYj0tNSQuCg==',1);

-- algebra manual 13
INSERT INTO "public"."problems"("id","statement","type","answer_representation","answer_value","solution","category_id")
VALUES
(DEFAULT,E'ClNvbHZlIHRoZSBlcXVhdGlvbiAkeF4yK1xmcmFjezV9ezJ9eD1cZnJhY3szfXsyfSQsICR4XGluXG1hdGhiYntSfSQsIGFuZCB3cml0ZSBlYWNoIG9mIHRoZSBzb2x1dGlvbnMgaW4gdGhlIGZvcm0gb2YgYW4gaW50ZWdlciBvciBhcyBhbiBpcnJlZHVjaWJsZSBxdW90aWVudCBvZiB0d28gaW50ZWdlcnMuCg==',E'manual_unordered',E'CiR4PVxmcmFjezF9ezJ9JCBvciAkeD0tMyQK',E'{x1,0.5,x2,-3}',E'ClRoZXJlIGFyZSBudW1lcm91cyB3YXlzIHRvIHNvbHZlIHRoZSBnaXZlbiBlcXVhdGlvbi4gVGhlIGZvbGxvd2luZyBpcyBvbmUgbmF0dXJhbCBhcHByb2FjaDoKXGJlZ2lue2FsaWduKn0KeF4yK1xmcmFjezV9ezJ9eD1cZnJhY3szfXsyfQomXGlmZiAyeF4yKzV4LTM9MCAmIFx0ZXh0eyhtdWx0aXBseSB0aHJvdWdoIGJ5IDIpfVxcWzFlbV0KJlxpZmYgMnheMis2eC14LTM9MCAmIFx0ZXh0eyhzdHJhdGVnaWNhbGx5IHJld3JpdGUpfVxcWzFlbV0KJlxpZmYgMngoeCszKS0oeCszKT0wICYgXHRleHR7KGZhY3Rvcil9XFxbMWVtXQomXGlmZiAoMngtMSkoeCszKT0wLiAmIFx0ZXh0eyhncm91cCBsaWtlIHRlcm1zKX0KXGVuZHthbGlnbip9CkZyb20gdGhlIGFib3ZlLCB3ZSBjYW4gc2VlIHRoYXQgdGhlIGdpdmVuIGVxdWF0aW9uIGlzIHNvbHZlZCB3aGVuIGVpdGhlciAkeD1cZnJhY3sxfXsyfSQgb3IgJHg9LTMkLgo=',1);

-- algebra manual 14
INSERT INTO "public"."problems"("id","statement","type","answer_representation","answer_value","solution","category_id")
VALUES
(DEFAULT,E'ClRoZSBleHByZXNzaW9uCiQkClxmcmFje3grMS1cZGZyYWN7MX17eCsxfX17XGRmcmFjezF9e3grMX19LAokJApzdWNoIHRoYXQgJHhcbmVxLTEkLCBjYW4gYmUgd3JpdHRlbiBpbiB0aGUgZm9ybSAkYXheMitieCQuIEV4cHJlc3MgJGEkIGFuZCAkYiQgYXMgaW50ZWdlcnMuCg==',E'manual_ordered',E'CiRhPTEkIGFuZCAkYj0yJAo=',E'{a,1,b,2}',E'Ck9uZSBhcHByb2FjaCBpcyB0byBtdWx0aXBseSB0aGUgZ2l2ZW4gZXhwcmVzc2lvbiBieSAkXGZyYWN7eCsxfXt4KzF9JCBhdCB0aGUgb3V0c2V0OgpcYmVnaW57YWxpZ24qfQpcZnJhY3t4KzEtXGRmcmFjezF9e3grMX19e1xkZnJhY3sxfXt4KzF9fQomPSBcZnJhY3t4KzEtXGRmcmFjezF9e3grMX19e1xkZnJhY3sxfXt4KzF9fVxjZG90XGZyYWN7eCsxfXt4KzF9ICYgXHRleHR7KHN0cmF0ZWdpY2FsbHkgbXVsdGlwbHkpfVxcWzFlbV0KJj0gXGJpZ2dsKHgrMS1cZnJhY3sxfXt4KzF9XGJpZ2dyKVxjZG90KHgrMSkgJiBcdGV4dHsoc2ltcGxpZnkpfVxcWzFlbV0KJj0geCh4KzEpKzEoeCsxKS0xICYgXHRleHR7KGRpc3RyaWJ1dGUpfVxcWzFlbV0KJj0geF4yKzJ4LiAmIFx0ZXh0eyhzaW1wbGlmeSl9ClxlbmR7YWxpZ24qfQpBbm90aGVyIGFwcHJvYWNoIGlzIHRvIGZpcnN0IG9idGFpbiBhIGNvbW1vbiBkZW5vbWluYXRvciBmb3IgdGhlIGV4cHJlc3Npb24gaW4gdGhlIG51bWVyYXRvciBhbmQgdGhlbiBtdWx0aXBseSB0aHJvdWdoIGJ5ICRcZnJhY3t4KzF9e3grMX0kOgpcYmVnaW57YWxpZ24qfQpcZnJhY3t4KzEtXGRmcmFjezF9e3grMX19e1xkZnJhY3sxfXt4KzF9fQomPSBcZnJhY3tcZGZyYWN7KHgrMSleMi0xfXt4KzF9fXtcZGZyYWN7MX17eCsxfX0gJiBcdGV4dHsoY29tbW9uIGRlbm9taW5hdG9yKX1cXFsxZW1dCiY9IFxmcmFje1xkZnJhY3t4XjIrMnh9e3grMX19e1xkZnJhY3sxfXt4KzF9fSAmIFx0ZXh0eyhzaW1wbGlmeSl9XFxbMWVtXQomPSBcZnJhY3tcZGZyYWN7eF4yKzJ4fXt4KzF9fXtcZGZyYWN7MX17eCsxfX1cY2RvdFxmcmFje3grMX17eCsxfSAmIFx0ZXh0eyhzdHJhdGVnaWNhbGx5IG11bHRpcGx5KX1cXFsxZW1dCiY9IHheMisyeC4KXGVuZHthbGlnbip9CkZyb20gdGhlIGFib3ZlLCBpdCBpcyBjbGVhciB0aGF0IGJvdGggYXBwcm9hY2hlcyBhcmUgc2ltaWxhciwgYWxiZWl0IHRoZSBzZWNvbmQgYXBwcm9hY2ggc2VlbXMgdG8gYmUgYW4gYWxnZWJyYWljYWxseSBjbGVhbmVyIGFwcHJvYWNoLiBSZWdhcmRsZXNzLCBpbiB0aGUgZW5kLCAkYT0xJCBhbmQgJGI9MiQuCg==',1);

-- algebra truefalse 10
INSERT INTO "public"."problems"("id","statement","type","answer_representation","answer_value","solution","category_id")
VALUES
(DEFAULT,E'CklmICRhJCwgJGIkLCBhbmQgJGMkIGRlbm90ZSByZWFsIG51bWJlcnMgYW5kICRwKHgpPWF4XjIrYngrYyQsICR4XGluXG1hdGhiYntSfSQsIHRoZW4gdGhlcmUgZXhpc3RzIGEgcmVhbCBudW1iZXIgJHhfMCQgc3VjaCB0aGF0ICRwKHhfMCk9MCQuCg==',E'truefalse',E'CkZhbHNlCg==',E'{F}',E'ClRoZSBpbXBvcnRhbnQgdGhpbmcgaGVyZSBpcyB0byByZWFsbHkgdW5kZXJzdGFuZCB3aGF0IHRoZSBzdGF0ZW1lbnQgaXMgY2xhaW1pbmcuIFRoZSBzdGF0ZW1lbnQgaXMgZXNzZW50aWFsbHkgYXNzZXJ0aW5nIHRoYXQgZXZlcnkgcXVhZHJhdGljIGVxdWF0aW9uIGhhcyBhIHJlYWwgemVyby4gUGVyaGFwcyBldmVuIG1vcmUgY2xlYXJseSwgdGhlIHN0YXRlbWVudCBpcyBhc3NlcnRpbmcgdGhhdCA8ZW0+ZXZlcnk8L2VtPiBwYXJhYm9sYSBpbnRlcnNlY3RzIHRoZSAkeCQtYXhpcyBpbiBhdCBsZWFzdCBvbmUgcGxhY2UuIFRoaXMgaXMsIG9mIGNvdXJzZSwgZmFsc2UuIFNpbXBseSBjb25zaWRlciBhbnkgcXVhZHJhdGljICRheF4yK2J4K2MkIHdoZXJlICRiXjItNGFjIDwgMCQgKGkuZS4sIHdoZW4gdGhlIDxlbT5kaXNjcmltaW5hbnQ8L2VtPiBpcyBuZWdhdGl2ZSkuIFN1Y2ggYSBxdWFkcmF0aWMgd2lsbCBub3QgaGF2ZSBhbnkgcmVhbCB6ZXJvcy4gRm9yIGV4YW1wbGUsIHRoZSBwYXJhYm9sYSAkeF4yKzEkIGRvZXMgbm90IGhhdmUgYW55IHJlYWwgemVyb3MuCg==',1);

-- inequalities manual 7
INSERT INTO "public"."problems"("id","statement","type","answer_representation","answer_value","solution","category_id")
VALUES
(DEFAULT,E'ClRoZSBzZXQgb2YgcmVhbCBudW1iZXJzICR5JCBzdWNoIHRoYXQgJHx5KzJ8PjIkIGNvbnNpc3RzIG9mIHR3byBvcGVuIGludGVydmFscywgb25lIG9mIHRoZSBmb3JtICQoLVxpbmZ0eSxhKSQgYW5kIG9uZSBvZiB0aGUgZm9ybSAkKGIsXGluZnR5KSQsIHdoZXJlICRhPCBiJC4gRXhwcmVzcyAkYSQgYW5kICRiJCBhcyBpbnRlZ2Vycy4K',E'manual_ordered',E'CiRhPS00JCBhbmQgJGI9MCQK',E'{a,-4,b,0}',E'CkJ5IHRoZSBkZWZpbml0aW9uIG9mIHRoZSBhYnNvbHV0ZSB2YWx1ZSBmdW5jdGlvbiwgd2UgaGF2ZQokJAp8eSsyfD0KXGJlZ2lue2Nhc2VzfQp5KzIgJiBcdGV4dHtpZn1cIHlcZ2VxLTIsXFwKLSh5KzIpICYgXHRleHR7aWZ9XCB5PC0yLgpcZW5ke2Nhc2VzfQokJApJbiB0aGUgY29udGV4dCBvZiB0aGlzIHByb2JsZW0sIHRoaXMgbWVhbnMgZWl0aGVyCiQkCnkrMj4yXGlmZiB5PjAKJCQKb3IKJCQKLSh5KzIpPjJcaWZmIHkrMjwtMlxpZmYgeTwtNC4KJCQKVGhhdCBpcywgdGhlIHR3byBvcGVuIGludGVydmFscyBhcmUgJCgtXGluZnR5LC00KSQgYW5kICQoMCxcaW5mdHkpJC4gSGVuY2UsICRhPS00JCBhbmQgJGI9MCQuCg==',2);

-- inequalities manual 11
INSERT INTO "public"."problems"("id","statement","type","answer_representation","answer_value","solution","category_id")
VALUES
(DEFAULT,E'ClRoZSBzZXQgb2YgcmVhbCBudW1iZXJzICR6JCBzdWNoIHRoYXQgJHo8IDAkIGFuZCAkXGZyYWN7MX17en0rXGZyYWN7en17Mn0+XGZyYWN7LTN9ezJ9JCBpcyBhbiBvcGVuIGludGVydmFsIG9mIHRoZSBmb3JtICQoYSxiKSQuIEV4cHJlc3MgJGEkIGFuZCAkYiQgYXMgaW50ZWdlcnMuCg==',E'manual_ordered',E'CiRhPS0yJCBhbmQgJGI9LTEkCg==',E'{a,-2,b,-1}',E'CkNvbnNpZGVyIHRoZSBmb2xsb3dpbmc6ClxiZWdpbnthbGlnbip9ClxmcmFjezF9e3p9K1xmcmFje3p9ezJ9PlxmcmFjey0zfXsyfQomXGlmZiBcZnJhY3sxfXt6fStcZnJhY3t6fXsyfStcZnJhY3szfXsyfT4wICYgXHRleHR7KGFkZCAkMy8yJCB0byBib3RoIHNpZGVzKX1cXFsxZW1dCiZcaWZmIFxmcmFjezJ9e3p9K3orMz4wICYgXHRleHR7KG11bHRpcGx5IHRocm91Z2ggYnkgMil9XFxbMWVtXQomXGlmZiBcZnJhY3syK3peMiszen17en0+MCAmIFx0ZXh0eyhjb21tb24gZGVub21pbmF0b3IpfVxcWzFlbV0KJlxpZmYgel4yKzN6KzI8IDAgJiBcdGV4dHsobXVsdGlwbHkgdGhyb3VnaCBieSAkeiQ7ICR6PCAwJCl9XFxbMWVtXQomXGlmZiAoeisxKSh6KzIpPCAwLiAmIFx0ZXh0eyhmYWN0b3IpfQpcZW5ke2FsaWduKn0KRnJvbSB0aGUgYWJvdmUsIGlzIGNsZWFyIHRoYXQgd2UgaGF2ZSBhIHBhcmFib2xhIHRoYXQgb3BlbnMgdXB3YXJkIHdpdGggemVyb3MgYXQgJHo9LTIkIGFuZCAkej0tMSQuIEl0IGlzIGZhaXJseSBjbGVhciB0aGF0IHdlIG11c3QgaGF2ZSAkelxpbigtMiwtMSkkLgo=',2);

-- inequalities truefalse 12
INSERT INTO "public"."problems"("id","statement","type","answer_representation","answer_value","solution","category_id")
VALUES
(DEFAULT,E'CklmIHRoZSB0d28gbm9uLXplcm8gcmVhbCBudW1iZXJzICRhJCBhbmQgJGIkIGFyZSBvcmRlcmVkIGJ5ICRhPCBiJCwgdGhlbiAkXGZyYWN7MX17Yn08XGZyYWN7MX17YX0kLgo=',E'truefalse',E'CkZhbHNlCg==',E'{F}',E'CkNvbnNpZGVyICRhPS0xJCBhbmQgJGI9MSQuIFRoZW4gJC0xPCAxJCwgYnV0CiQkClxmcmFjezF9e2J9PVxmcmFjezF9ezF9PTFcbm90PC0xPVxmcmFjezF9ey0xfT1cZnJhY3sxfXthfS4KJCQK',2);

-- inequalities truefalse 14
INSERT INTO "public"."problems"("id","statement","type","answer_representation","answer_value","solution","category_id")
VALUES
(DEFAULT,E'ClRoZSBzZXQgb2YgcmVhbCBudW1iZXJzICR4JCB0aGF0IHNhdGlzZnkgYm90aCAkfHgrMnw8IDQkIGFuZCAkfHgtNXw8IDQkIGlzIHRoZSBlbXB0eSBzZXQuCg==',E'truefalse',E'CkZhbHNlCg==',E'{F}',E'Ck5vdGUgdGhhdAokJAp8eCsyfDwgNFxpZmYgLTQ8IHgrMjwgNFxpZmYgLTY8IHggPCAyCiQkCmFuZAokJAp8eC01fDwgNFxpZmYgLTQ8IHgtNTwgNFxpZmYgMTwgeDwgOS4KJCQKVGhlIGZpcnN0IGluZXF1YWxpdHkgaXMgdHJ1ZSB3aGVuICR4XGluKC02LDIpJCBhbmQgdGhlIHNlY29uZCBpbmVxdWFsaXR5IGlzIHRydWUgd2hlbiAkeFxpbigxLDkpJC4gSGVuY2UsIDxlbT5ib3RoPC9lbT4gaW5lcXVhbGl0aWVzIHdpbGwgYmUgdHJ1ZSB3aGVuIHRoZXNlIHNvbHV0aW9uIHNldHMgb3ZlcmxhcDsgdGhhdCBpcywgYm90aCBpbmVxdWFsaXRpZXMgd2lsbCBiZSB0cnVlIHdoZW4KJCQKeFxpbigtNiwyKVxjYXAoMSw5KVxpZmYgeFxpbigxLDIpLiAKJCQKVGh1cywgY2hvb3NpbmcgPGVtPmFueTwvZW0+ICR4XGluKDEsMikkIHdpbGwgc2VydmUgYXMgYSBjb3VudGVyIGV4YW1wbGUgZm9yIHRoZSBjbGFpbSBpbiBxdWVzdGlvbiAodGhhdCBpcywgYW55ICR4XGluKDEsMikkIHdpbGwgc2F0aXNmeSBib3RoIGluZXF1YWxpdGllcykuCg==',2);

-- logarithms manual 11
INSERT INTO "public"."problems"("id","statement","type","answer_representation","answer_value","solution","category_id")
VALUES
(DEFAULT,E'CkV4cHJlc3MgYXMgYW4gaW50ZWdlciB0aGUgdmFsdWUgb2YgJChcc3FydFszXXs5fSkoMyleey0yLzN9JC4K',E'manual_unordered',E'CjEK',E'{1}',E'CkNvbnNpZGVyIHRoZSBmb2xsb3dpbmc6CiQkCihcc3FydFszXXs5fSkoMyleey0yLzN9PSgzKV57Mi8zfSgzKV57LTIvM309M14wPTEuCiQkCg==',4);

-- logarithms manual 16
INSERT INTO "public"."problems"("id","statement","type","answer_representation","answer_value","solution","category_id")
VALUES
(DEFAULT,E'CkV4cHJlc3MgYXMgYW4gaW50ZWdlciB0aGUgdmFsdWUgb2YgJFxhbHBoYSQgdGhhdCBzYXRpc2ZpZXMgJCgyXntcbG9nXzQgMn0pKDRee1xsb2dfMiA0fSk9Ml57XGFscGhhLzJ9JC4K',E'manual_unordered',E'CiRcYWxwaGE9OSQK',E'{alpha,9}',E'CkZpcnN0IG5vdGUgdGhhdCAkXGxvZ180IDI9XGZyYWN7MX17Mn0kIHNpbmNlICQ0XntcZnJhY3sxfXsyfX09MiQgYW5kICRcbG9nXzIgND0yJCBzaW5jZSAkMl4yPTQkLiBUaHVzLAokJAooMl57XGxvZ180IDJ9KSg0XntcbG9nXzIgNH0pPSgyXnsxLzJ9KSg0XnsyfSk9KDJeezEvMn0pKDJeNCk9Ml57OS8yfS4KJCQKSGVuY2UsICRcYWxwaGE9OSQuCg==',4);

-- logarithms truefalse 12
INSERT INTO "public"."problems"("id","statement","type","answer_representation","answer_value","solution","category_id")
VALUES
(DEFAULT,E'CiQ0XlxwaT0zXntccGlcbG9nXzMgNH0kCg==',E'truefalse',E'ClRydWUK',E'{T}',E'CkNvbnNpZGVyIHRoZSBmb2xsb3dpbmc6ClxiZWdpbnthbGlnbip9CjNee1xwaVxsb2dfMyA0fQomPTNee1xsb2dfMyAoNF5ccGkpfSAmIFx0ZXh0eyhwb3dlciBsYXcpfVxcWzFlbV0KJj00XlxwaS4gJiBcdGV4dHsoaW52ZXJzZXMpfQpcZW5ke2FsaWduKn0K',4);

-- logarithms truefalse 13
INSERT INTO "public"."problems"("id","statement","type","answer_representation","answer_value","solution","category_id")
VALUES
(DEFAULT,E'CkxldCAkeCQgZGVub3RlIGEgcG9zaXRpdmUgcmVhbCBudW1iZXIuIElmICRhJCBhbmQgJGIkIGRlbm90ZSByZWFsIG51bWJlcnMsIHRoZW4gJCh4XmEpKHheYik9eF57YWJ9JC4K',E'truefalse',E'CkZhbHNlCg==',E'{F}',E'CkNvbnNpZGVyIHRoZSBjYXNlIHdoZW4gJHg9MiQsICRhPTIkLCBhbmQgJGI9MyQuIFRoZW4KJCQKKHheYSkoeF5iKT0oMl4yKSgyXjMpPSg0KSg4KT0zMiwKJCQKYnV0CiQkCnhee2FifT0yXnsyXGNkb3QzfT0yXjY9NjQuCiQkCg==',4);

-- trigonometry manual 5
INSERT INTO "public"."problems"("id","statement","type","answer_representation","answer_value","solution","category_id")
VALUES
(DEFAULT,E'CkZvciBzb21lIHZhbHVlIG9mICRcdGhldGEkIGluIHRoZSBpbnRlcnZhbCAkWzAsXHBpXSQsIHRoZSB2YWx1ZSBvZiAkXGNvcyhcdGhldGEpJCBpcyAkLVxmcmFjezF9ezJ9JC4gVGhlIHZhbHVlIG9mICRcdGhldGEkIGNhbiBiZSB3cml0dGVuIGluIHRoZSBmb3JtICRcYWxwaGFccGkkLiBFeHByZXNzIHRoZSB2YWx1ZSBvZiAkXGFscGhhJCBpbiBzaW1wbGVzdCBmb3JtIChhcyBhbiBpcnJlZHVjaWJsZSBxdW90aWVudCBvZiB0d28gaW50ZWdlcnMpLgo=',E'manual_unordered',E'CiRcYWxwaGE9XGZyYWN7Mn17M30kCg==',E'{alpha,0.667}',E'CklmICRcdGhldGFcaW5bMCxccGldJCBhbmQgJFxjb3NcdGhldGEkIGlzIG5lZ2F0aXZlLCB0aGVuICRcdGhldGEkIG11c3QgcmVzaWRlIGluIHRoZSBzZWNvbmQgcXVhZHJhbnQuIFNpbmNlICRcY29zXHRoZXRhPS1cZnJhY3sxfXsyfSQsIGFuZCAkXGNvcyhccGkvMyk9XGZyYWN7MX17Mn0kIChyZW1lbWJlciwgeW91IDxlbT5hbHdheXM8L2VtPiB3YW50IHRvIHVzZSB0aGUgZmlyc3QgcXVhZHJhbnQgYXMgYSByZWZlcmVuY2UgcG9pbnQ7IHRoZSByZWZlcmVuY2UgbnVtYmVyIGhlcmUgJFxwaS8zJCksIGl0IGZvbGxvd3MgdGhhdCAkXGNvcygyXHBpLzMpPS1cZnJhY3sxfXsyfSQuCg==',3);

-- trigonometry manual 7
INSERT INTO "public"."problems"("id","statement","type","answer_representation","answer_value","solution","category_id")
VALUES
(DEFAULT,E'CkV4cHJlc3MgYXMgYW4gaW50ZWdlciB0aGUgdmFsdWUgb2YgJFx0YW5cYmlnbChcc2luXnstMX1cYmlnbChcZnJhY3sxfXtcc3FydHsyfX1cYmlncilcYmlncikkLgo=',E'manual_unordered',E'CjEK',E'{1}',E'Ckl0IG1heSBoZWxwIHRvIHJlYWQgJFxzaW5eey0xfSgxL1xzcXJ0ezJ9KSQgYXMgInNpbmUgb2Ygd2hhdCBnaXZlcyAkMS9cc3FydHsyfSQuIiBTaW5jZSB0aGlzICJ3aGF0IiBtdXN0IGJlIGJldHdlZW4gJC1ccGkvMiQgYW5kICRccGkvMiQgKHJlY2FsbCB0aGUgcmVzdHJpY3RlZCBkb21haW4gb2Ygc2luZSBzbyB0aGF0IHNpbmUgaGFzIGFuIGludmVyc2UpLCBpdCBmb2xsb3dzIHRoYXQgdGhlICJ3aGF0IiBpbiB0aGlzIGNhc2UgaXMgJFxwaS80JCBzaW5jZSAkXHNpbihccGkvNCk9MS9cc3FydHsyfSQuIFRodXMsIHdlIGhhdmUKJCQKXHRhblxiaWdnbChcc2luXnstMX1cYmlnZ2woXGZyYWN7MX17XHNxcnR7Mn19XGJpZ2dyKVxiaWdncik9XHRhbihccGkvNCk9MS4KJCQK',3);

-- trigonometry truefalse 1
INSERT INTO "public"."problems"("id","statement","type","answer_representation","answer_value","solution","category_id")
VALUES
(DEFAULT,E'ClRoZSBmdW5jdGlvbiAkXHNpbih4KSQgaXMgZGVmaW5lZCBmb3IgYWxsIHJlYWwgdmFsdWVzIG9mICR4JC4K',E'truefalse',E'ClRydWUK',E'{T}',E'ClJlY2FsbCBvbmUgb2YgdGhlIG1vc3QgY29tbW9uIGRlZmluaXRpb25zIG9mIHRoZSBzaW5lIGZ1bmN0aW9uOiBMZXQgJHQkIGJlIGFueSByZWFsIG51bWJlciBhbmQgbGV0ICRQKHgseSkkIGJlIHRoZSB0ZXJtaW5hbCBwb2ludCBvbiB0aGUgdW5pdCBjaXJjbGUgZGV0ZXJtaW5lZCBieSAkdCQuIFRoZW4gJFxzaW4odCk9eSQ7IHRoYXQgaXMsICRcc2luKHQpJCBnaXZlcyB1cyB0aGUgJHkkLWNvb3JkaW5hdGUgb2YgdGhlIHRlcm1pbmFsIHBvaW50ICRQJC4gU2luY2UgdGhpcyB0ZXJtaW5hbCBwb2ludCB3aWxsIHJlc3VsdCBmcm9tIGFueSAkdFxpblxtYXRoYmJ7Un0kLCBpdCBuYXR1cmFsbHkgZm9sbG93cyB0aGF0ICRcc2luKHQpJCBpcyBkZWZpbmVkIGZvciBhbGwgcmVhbCB2YWx1ZXMgJHQkLiAoSW4gdGhlIGNvbnRleHQgb2YgdGhpcyBwcm9ibGVtLCB0aGlzIG1lYW5zIHRoYXQsIG9mIGNvdXJzZSwgJFxzaW4oeCkkIGlzIGRlZmluZWQgZm9yIGFsbCByZWFsIHZhbHVlcyBvZiAkeCQuKQo=',3);

-- trigonometry truefalse 3
INSERT INTO "public"."problems"("id","statement","type","answer_representation","answer_value","solution","category_id")
VALUES
(DEFAULT,E'CkZvciAkLVxmcmFje1xwaX17Mn08IHg8IFxmcmFje1xwaX17Mn0kLCBpdCBmb2xsb3dzIHRoYXQgJFx0YW4oeClcY29zKHgpPVxzaW4oeCkkLgo=',E'truefalse',E'ClRydWUK',E'{T}',E'ClNpbmNlICRcdGFuKHgpPVxmcmFje1xzaW4oeCl9e1xjb3MoeCl9JCBhbmQgJFxjb3MoeClcbmVxMCQgd2hlbiAkeFxpbigtXHBpLzIsXHBpLzIpJCwgd2UgaGF2ZSB0aGUgZm9sbG93aW5nOgokJApcdGFuKHgpXGNvcyh4KT1cZnJhY3tcc2luKHgpfXtcY29zKHgpfVxjb3MoeCk9XHNpbih4KS4KJCQK',3);